---

- name: Add repository for Ruby 'ppa:brightbox/ruby-ng'
  apt_repository: repo='ppa:brightbox/ruby-ng' mode=0644 update_cache=yes state=present

- name: Installing ruby2.1
  apt: name=ruby2.1 state=present

- name: mkdir -p {{ ruby_2_1_executable_gem_path }}
  file: path={{ ruby_2_1_executable_gem_path }} state=directory

- name: Installing bundler in {{ ruby_2_1_executable_gem_path }} 
  command: gem2.1 install bundler --bindir {{ ruby_2_1_executable_gem_path }}

- name: Creating symlink of src="{{ ruby_2_1_executable_gem_path }}/bundle"  dest={{ system_bundle_path }}
  file: src="{{ ruby_2_1_executable_gem_path }}/bundle"  dest={{ system_bundle_path }} mode=0755 owner=root group=root state=link

- name: Creating symlink of src="{{ ruby_2_1_executable_gem_path }}/bundler"  dest={{ system_bundler_path }}
  file: src="{{ ruby_2_1_executable_gem_path }}/bundler"  dest={{ system_bundler_path }} mode=0755 owner=root group=root state=link
  


