---
- name: Creating a deployers group for deployment
  group: name=deployers state=present

- name: Giving deployers group root privileges
  lineinfile: dest=/etc/sudoers state=present regexp='^%deployers ALL\=' line='%deployers ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: Creating a deploy user for deployment
  user: name=deploy state=present group=deployers

- name: Creating a directorty at deployment path
  file: path=/home/vagrant/application state=directory owner=deploy group=deployers mode=0744
